### ISSUE TITLE
interop with C++ std::string

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/octh#28]
The string interop is not currently correct. I'm not sure why I thought this might work. 
``` rust
    let name = CString::new("helloworld").unwrap();
    let pname = name.as_ptr() as *const octh::root::std::string;
    std::mem::forget(pname);
```
https://github.com/ctaggart/octh_examples/blob/723cfaf9fc6d16e0c0caec6148ecf1e1dbc62831/src/lib.rs#L11-L13

I think we have to disable `.opague_type("std::.*")` in build.rs in order to create bindgen for `std::string`. This opens up a can of worms though:

- [x] #27 rustfmt errors when std:: enabled
- [x] #29 error[E0428]: the name `sentry` is defined multiple times
- [x] #8 cannot find type `_CharT` in this scope

**Comment by mtmiller** [comment]
Much of the Octave API uses std::strings, so I think this will be pretty much required to get a useful binding working anyway. Even if you could get past the function call registration part of this, it would be hard to get the value of a string argument passed in to your function without std::string.

**Comment by ctaggart** [comment]
Reviewing this two years later, it looks like I should pursue the answer to the question I asked at  https://stackoverflow.com/q/46524781/23059 

I think I'm doing the interop wrong [here](https://github.com/ctaggart/octave-add/blob/db1658f78bfbc3f1b1a0ee663e7bc3994283bd49/src/lib.rs#L10-L18) for #18:

``` rust
    let name = CString::new("add").unwrap();
    let pname = name.as_ptr() as *const octh::root::std::string;
    std::mem::forget(pname);

    let doc = CString::new("adds inputs and returns sum to all outputs").unwrap();
    let pdoc = doc.as_ptr() as *const octh::root::std::string;
    std::mem::forget(pdoc);
    
    let fcn = octh::root::octave_dld_function_create(Some(Fadd), shl, pname, pdoc);
```

It is creating `char*`, but those are not `std::string` and the cast is bad. Based on https://www.geeksforgeeks.org/convert-character-array-to-string-in-c/ may be this will work:

``` cpp
string string_create(char* a)
{
    string s(a);
    return s;
}
```

Or wrap `octave_dld_function_create` to use have `pname` and `pdoc` by `char*`.
